### ISSUE TITLE
sys included in response even though I didn't specify for it to be in webhook response

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#239]
Why is sys being added to everything?

```
{
  "textResponse": "Hello tomorrow",
  "slots": {
    "New slot 1": "",
    "New slot 2": "",
    "New slot 3": {
      "value": "tomorrow",
      "original": "tomorrow"
    },
    "sys": {
      "duckling_time": {
        "from": "2018-06-03T00:00:00Z",
        "to": "2018-06-04T00:00:00Z",
        "original": "tomorrow"
      },
      "duckling_amount-of-money": ""
    },
    "sys.duckling_amount-of-money": ""
  }
}
```

**Comment by dcalvom** [comment]
When a system entity is recognized it is added to the sys attribute inside the slots. Regarding on the second "sys.duckling_amount-of-money" I assume that you created a slot with by tagging some text with sys.duckling_amount-of-money entity, therefore a named slot is created with that name.

**Comment by wrathagom** [comment]
but if we now allow formatting the response, shouldn't it be up to the user to include sys or not?

**Comment by dcalvom** [comment]
Yeah, but that would imply something else. Right the sys entities are part of the default response in the parse method, that's why when you include {{{JSONstringify slots}}} in the Response definition all the sys slots are included.

**Comment by wrathagom** [comment]
but those aren't slots those are entities

**Comment by dcalvom** [comment]
That's true!...then we need to design the response. By default, I was including those in the slots, but now I don't remember if that was because of a special reason. I will check it out, by the moment let me know if you have something in mind for this change.

**Comment by wrathagom** [comment]
My vote is just to remove it from the slots. If we still want access to it we add it to the root of the CSO.

**Comment by dcalvom** [comment]
Ok! Sounds good

**Comment by wrathagom** [comment]
Fixed in a branch with commit 309b22fbbaef8278363a10f1269b4ce48036f47e

**Comment by dcalvom** [comment]
This is still missing when the scenario doesn't have slots. This happens in the line 151 in the RespondIntent tool in the agent tools. We are not going to fix this yet, until malave refactoring.
