### ISSUE TITLE
Theshold goes to zero after saving

### ISSUE THREAD

**Issue by wrathagom** [samtecspg/articulate#532]
When saving the category page the threshold goes to zero and doesn't come back

![image](https://user-images.githubusercontent.com/1779894/52133646-bedc8a00-260f-11e9-9043-dc8085c78376.png)

**Comment by dcalvom** [comment]
Fixed by https://github.com/samtecspg/articulate/commit/1e591f569597d395ef0df16b292985e3b37dbdc8

**Comment by wrathagom** [comment]
@dcalvom I am still seeing this behavior on the Category screen.

**Comment by wrathagom** [comment]
![image](https://user-images.githubusercontent.com/1779894/52223516-c69c6880-2873-11e9-9302-bf8f61208a0a.png)

**Comment by dcalvom** [comment]
Closed by https://github.com/samtecspg/articulate/commit/0bc8e27ba9f677113c1682d1cb9f0a8eb6db4055
